before:
  hooks:
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
archive:
  replacements:
    darwin: MacOS
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brew:
  github:
    owner: Arkweid
    name: websocket-bench-homebrew-tap
  homepage: "https://github.com/Arkweid/websocket-bench"
  description: "CLI interface for benchmark AnyCable"
  folder: Formula
  test: |
    system "#{bin}/websocket-bench -h"

nfpm:
  name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  "https://github.com/Arkweid/websocket-bench"
  description: CLI interface for benchmark AnyCable
  maintainer: Alexander Abroskin <arkweid@evilmartians.com>
  license: MIT
  vendor: Arkweid
  formats:
  - deb
  - rpm
  recommends:
  - rpm
