dist: trusty
sudo: required
language: go
go: '1.12.x'

addons:
  apt:
    packages:
    - rpm

script: skip

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true

notifications:
  email: false
